import type { Metadata } from 'next';

import { createClient } from '@/libs/supabase/server';
import { type PropsWithChildren } from '@/types/common';

import { bodoniModa, inter } from './fonts';
import { Initializer } from './initializer';
import { RootLayoutProvider } from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const supabase = await createClient();

  const { data } = await supabase.auth.getUser();

  return (
    <html lang="en" className={`${bodoniModa.variable} ${inter.variable}`}>
      <body className={inter.className}>
        <RootLayoutProvider user={data.user}>
          {children}
          <Initializer />
        </RootLayoutProvider>
      </body>
    </html>
  );
}
