import type { Metadata } from 'next';

import { type PropsWithChildren } from '@/types/common';

import { Initializer } from './initializer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="h-[2000px]">
        {children}
        <Initializer />
      </body>
    </html>
  );
}
